### ISSUE TITLE
on_error gets triggered on every input field click in dom

### ISSUE THREAD

**Issue by ashwani-idealz** [grantm/jquery-datetextentry#13]
on_error event gets triggered on every input field click in dom, unable to debug the root cause.
This does not happen if you are focused on some other element and then click on other input elements.
But instead gets triggered after you click on datetext field and then you start to click on other input fields.

**Comment by grantm** [comment]
When the focus leaves one of the widget's sub fields, that usually indicates the user has finished entering data in that field, so the validation is triggered. Regardless of whether there is an error, your `on_error` callback will be called and passed the error description text. If there is no error, then the description text will be an empty string.

This does mean that the `on_error` handler is called frequently, but that is so that your error handler can determine if you consider it an error and how you want to handle it.
